FROM osrf/ros:foxy-ros1-bridge

USER root
RUN echo "root:root" | chpasswd && \
    adduser --disabled-password --gecos "" "ubuntu" && \
    echo "ubuntu:ubuntu" | chpasswd && \
    echo "%ubuntu    ALL=(ALL)   NOPASSWD:    ALL" >> /etc/sudoers.d/ubuntu && \
    chmod 0440 /etc/sudoers.d/ubuntu
RUN apt-key del 421C365BD9FF1F717815A3895523BAEEB01FA116 && \
    apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
RUN apt-get update && \
    apt-get install -y curl

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal InRelease" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -k https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | apt-key add -
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

USER ubuntu
WORKDIR /home/ubuntu
RUN bash -c "source /opt/ros/noetic/setup.bash"
RUN bash -c "source /opt/ros/foxy/setup.bash"
RUN sudo apt-get update && sudo apt-get install -y net-tools iputils-ping

RUN mkdir -p /home/ubuntu/catkin_ws/src

RUN mkdir -p /home/ubuntu/ros1_bridge_ws/src
WORKDIR /home/ubuntu/ros1_bridge_ws/src
WORKDIR /home/ubuntu/ros1_bridge_ws
RUN colcon build --symlink-install --packages-select ros1_bridge --cmake-force-configure
